"""Positive locking support

Revision ID: 49d3a3dd9f24
Revises: eddfb088cf3c
Create Date: 2025-10-21 18:40:51.578867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d3a3dd9f24'
down_revision: Union[str, Sequence[str], None] = 'eddfb088cf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('version_uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'version_uuid')
    # ### end Alembic commands ###
